### ISSUE TITLE
Allow multiple architectures, image tags for image builds

### ISSUE THREAD

**Issue by Chuxel** [devcontainers/ci#151]
The dev container CLI will soon support a platform argument, and https://github.com/devcontainers/cli/pull/61 introduces the ability to do multiple tags.

The challenge here is when you do a multiple architecture build, you can't use the image to run locally.  This makes me wonder if this should either be a separate action, or requires an optional `runCmd` as proposed with #150.

//cc @stuartleeks

**Comment by natescherer** [comment]
Just wanted to drop a note that I'm working on a PR to add this multiple architecture builds that I expect to wrap up within the next week or so.

**Comment by natescherer** [comment]
Discovered that this is currently blocked by https://github.com/devcontainers/cli/issues/155

**Comment by natescherer** [comment]
PR added to allow multi-platform builds. When/if it's accepted I have a plan for how to add multiple tag support, as well.

**Comment by joshspicer** [comment]
https://github.com/devcontainers/ci/pull/175 has been merged 👍

**Comment by natescherer** [comment]
Beat me to commenting! I'm now working on adding multiple tag support too.

**Comment by metaskills** [comment]
Should this be closed now?
