### ISSUE TITLE
How to include `ARM` support for M1 and linux-arm

### ISSUE THREAD

**Issue by Anselmoo** [devcontainers/ci#172]
Unfortunately, I got the following error:

```log
(linux/amd64) does not match the detected host platform (linux/arm64/v8)
```

if it is running on a MacOS with __M1__.

Does `devcontainer.ci` has an option to built the images via _matrix-built_?

thx

**Comment by Chuxel** [comment]
Multi architecture support is in https://github.com/devcontainers/ci/pull/175, though the underlying [devcontainer CLI](https://github.com/devcontainers/cli) supports it if you invoke that directly.
