### ISSUE TITLE
Docker inspect is failing

### ISSUE THREAD

**Issue by bhack** [devcontainers/ci#174]
I am trying to experiment this ACTION in a repository but `docker inspect` is failing:

https://github.com/keras-team/keras-cv/pull/893
https://github.com/keras-team/keras-cv/actions/runs/3219716266/jobs/5265457197

**Comment by joshspicer** [comment]
Hey @bhack! Based on your actions history on the repo it looks like this may be resolved?  Would you mind sharing if that is the case (and perhaps if you needed a work around we could explore surfacing that).

**Comment by bhack** [comment]
One version was merged but I don't remember if I've adopted a workaround as it was 1 month ago.

So I am closing  this
