### ISSUE TITLE
Cannot "build without cache" when `imageName` is specified

### ISSUE THREAD

**Issue by sarisia** [devcontainers/ci#182]
I want to build devcontainer image without using previous built image as a cache in order to
pull upstream image's updates, but specifiying `imageName` implies `cacheFrom` and seems
there's no way to disable this.

https://github.com/devcontainers/ci/blob/96af31b963e2ff6b5be0f96195a92f0c844c52b4/github-action/src/main.ts#L70-L78

**Comment by stuartleeks** [comment]
Hi @sarisia - I believe this should be resolved by https://github.com/devcontainers/ci/pull/199 which adds a `noCache` option to opt out of image caching
