### ISSUE TITLE
DevOps Task fails when using 'runCmd'

### ISSUE THREAD

**Issue by oliver7598** [devcontainers/ci#184]
All uses of the latest DevOps Marketplace extension (as of update 17/11/2022) are failing when the 'runCmd' parameter is provided.

Regardless of what is provided for the parameter, the following error is returned:
`Command failed: docker ps -q -a --filter label=devcontainer.local_folder=/home/vsts/work/1/s (exit code: undefined)`.

**Comment by stuartleeks** [comment]
@oliver7598 can you provide the snippet of your pipeline with the dev containers task in? Thanks!

**Comment by oliver7598** [comment]
It is part of a TRE deployment pipeline:
`- task: DevcontainersCi@0
        displayName: Show tools versions
        inputs:
          imageName: '$(mgmt_acr).azurecr.io/ouhtre-deployment-devcontainer'
          runCmd: |
            echo "Terraform version:"
            terraform --version
            
            echo
            echo "Porter version:"
            porter --version
            
            echo
            echo "Porter mixin versions:"
            porter mixin list
          env: |
            ARM_CLIENT_ID=$(ARM_CLIENT_ID)
            ARM_CLIENT_SECRET=$(ARM_CLIENT_SECRET)
            ARM_SUBSCRIPTION_ID=$(ARM_SUBSCRIPTION_ID)
            ARM_TENANT_ID=$(ARM_TENANT_ID)
            AAD_TENANT_ID=$(ARM_TENANT_ID)
            LOCATION=uksouth
            TF_VAR_location=uksouth
            TF_VAR_mgmt_resource_group_name=$(mgmt_resource_group)
            TF_VAR_mgmt_storage_account_name=$(mgmt_storage_account)
            TF_VAR_acr_name=$(mgmt_acr)
            TF_VAR_terraform_state_container_name=tfstate
            DEBUG=$(DEBUG)
            TRE_ID=$(tre_id)
            USE_ENV_VARS_NOT_FILES=true
            TF_IN_AUTOMATION=true
          push: 'never'`

Version details:
`Task         : Devcontainers CI Task
Description  : Build and run Dev Containers (https://containers.dev/) in Azure DevOps Pipelines
Version      : 0.2.1900000228
Author       : Devcontainers
Help         :`

**Comment by stuartleeks** [comment]
Thanks. There's nothing that particularly jumps out at me.

Could you try adding a stripped-down version and seeing whether that has the same behaviour?

```yaml
- task: DevcontainersCi@0
        displayName: Test
        inputs:
          imageName: devcontainer-test
          runCmd: |
            echo "hi"
          push: 'never' 
```

**Comment by oliver7598** [comment]
The pipeline is based off of the AzureTRE-Deployment repo.  The post create command is set to run `./.devcontainer/scripts/post-create.sh` although this does call `sudo bash AzureTRE/devops/scripts/set_docker_sock_permission.sh` at the end of the script.

**Comment by stuartleeks** [comment]
Can you try removing the call to `set_docker_sock_permission.sh` and running a build?
I think that attempts to patch up the permissions so that the user inside the dev container can access the docker socket, but unfortunately does it in a way that breaks the permissions for the user outside the container. I think the steps that the devcontainers/cli (which is what the Azure DevOps task builds on) takes to align the dev container user ID may mean that you don't need the script

**Comment by oliver7598** [comment]
@stuartleeks That seems to have resolved the issue!  It was the `set_docker_sock_permission.sh` causing the issue!  Thanks for the support!

**Comment by stuartleeks** [comment]
Glad that is working now! I've created #185 to track improving the error output
