### ISSUE TITLE
Handle GITHUB_OUTPUT

### ISSUE THREAD

**Issue by stuartleeks** [devcontainers/ci#188]
GitHub actions are deprecating the previous `set-output` approach for setting outputs in favour of echoing to `GITHUB_OUTPUT` ([link](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)) as flagged by @stephenandary in #180.

When run inside a dev container, the `GITHUB_OUTPUT` location is not accessible (even if the environment variable is set).

Proposed approach to handling this:
 - mount the host's `GITHUB_OUTPUT` location to `/mnt/github/output` inside the dev container
 - set the `GITHUB_OUTPUT` environment variable in the container to `/mnt/github/output`

This could be done automatically so that this just works as expected for users of the CI action.

Additionally, this approach could be adopted for `GITHUB_OUTPUT`, `GITHUB_STATE`, `GITHUB_ENV`, `GITHUB_STEP_SUMMARY`, and `GITHUB_PATH`

**Comment by stuartleeks** [comment]
This would require an update to `devcontainers/cli` ([link](https://github.com/devcontainers/cli/issues/327))

**Comment by stephenandary** [comment]
Can the CLI I handle multiple mount-points already? Asking based on language in description here: [devContainersSpecCLI.ts#L112](https://github.com/devcontainers/cli/blob/main/src/spec-node/devContainersSpecCLI.ts#L112)

**Comment by stuartleeks** [comment]
Yes, you're right!

**Comment by stephenandary** [comment]
Thank goodness haha. I like when things require less work! :laughing:

**Comment by joseviccruz** [comment]
+1!
I really need this feature ASAP

**Comment by joseviccruz** [comment]
Hi everyone, any updates here?

**Comment by stuartleeks** [comment]
I believe that @stephenandary is planning to handle this in #219
