### ISSUE TITLE
Re-enable `test_platform_with_runcmd` in Azure DevOps

### ISSUE THREAD

**Issue by stuartleeks** [devcontainers/ci#198]
As part of #140 the AzDO build is now triggered, but there is a failure in the execution of the `test_platform_with_runcmd` test, so it has temporarily been commented out in the pipeline. This issue is tracking fixing and re-enabling it.

```
[2023-01-24T14:42:36.350Z] #13 0.141 sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
```
[build log](https://dev.azure.com/monacotools/Monaco/_build/results?buildId=200691&view=logs&j=ef2e8ffe-dad2-56b1-d669-6ffbb47f4513&t=9479b45b-04de-5726-da4d-86d3f17be01a&l=247)

**Comment by stuartleeks** [comment]
Updating the `Dockerfile` for `test_platform_with_runcmd` to set `USER root`  before the `RUN` steps that use `sudo` seemed to workaround the `effective uid is not 0` error.

With that in place, there is an error in the `skopeo` copy stage:

```
time="2023-01-24T20:59:45Z" level=fatal msg="creating an updated image manifest: preparing updated manifest, layer \"sha256:d699ae6cb5d892663268ad8f5dff7f7122e0d32890571599485779b7596f0e0d\": unsupported MIME type for compression: application/vnd.in-toto+json"
```

According to [this issue](https://github.com/containers/skopeo/issues/1874), it may be resolved in later versions of skopeo. Next steps would be to check the version installed

**Comment by stuartleeks** [comment]
I was looking at the installed software on [GitHub runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners) and [AzDO runners](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml), and both have the same version 1.4.1 of skopeo. This is lower than the 1.9.0 that is suggested to work in https://github.com/containers/skopeo/issues/1874.

This confused me as the error only shows on the AzDO PR builds. However, I spotted that the issue does show in the GH builds on merge to main (it turns out the images aren't pushed on the PR builds).

Example: https://github.com/devcontainers/ci/actions/runs/4016076334/jobs/6898731939

So it looks like the skopeo issue would likely be resolved in GH & AzDO by installing a later skopeo version

**Comment by natescherer** [comment]
Just ran into this problem myself. https://github.com/containers/skopeo/issues/1646#issuecomment-1138779723 works for installing an updated skopeo version until the runner images can be updated.
