### ISSUE TITLE
Support devcontainer.json in sub-folder (`.devcontainer/**/devcontainer.json`)

### ISSUE THREAD

**Issue by eitsupi** [devcontainers/ci#212]
Does this CI work with `.devcontainer/**/devcontainer.json (where ** is a sub-folder)` from the specs?
https://containers.dev/implementors/spec/#devcontainerjson

The `subFolder` inputs does not seem to be match this case.

**Comment by stuartleeks** [comment]
Hi @eitsupi - do you have an example of where you tried this? (I had a quick scan down the linked issue but didn't spot it)

I'm curious as to whether the action attempted to call the `devcontainer` CLI. From a quick look back over the code, I didn't see anything that would stop it calling the CLI. If that is the case then it probably makes sense to open an issue on https://github.com/devcontainers/cli as that is the underpinning of the functionality in the action

**Comment by eitsupi** [comment]
Thanks for your response.

> Hi @eitsupi - do you have an example of where you tried this? (I had a quick scan down the linked issue but didn't spot it)

This commit and
https://github.com/PRQL/prql/pull/1893/commits/f4e25abff2cb4b1ce329e11f80a18ea42c67b2f5

This workflow log.
https://github.com/PRQL/prql/actions/runs/4253869385/jobs/7399324410

```log
🏗️ build container
  About to run devcontainer build --workspace-folder /home/runner/work/prql/prql/.devcontainer/base --image-name ghcr.io/prql/prql-devcontainer:latest --platform linux/amd64) --output type=oci,dest=/tmp/output.tar --cache-from ghcr.io/prql/prql-devcontainer:latest --cache-from ghcr.io/prql/prql-devcontainer
  [2023-02-23T14:57:25.754Z] @devcontainers/cli 0.30.0. Node.js v18.14.1. linux 5.15.0-1033-azure x64.
  
  Error: Dev container config (/home/runner/work/prql/prql/.devcontainer/base/.devcontainer/devcontainer.json) not found.
      at doe (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2069:26598)
      at async hoe (/usr/local/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:2069:25017)
```

> I'm curious as to whether the action attempted to call the `devcontainer` CLI. From a quick look back over the code, I didn't see anything that would stop it calling the CLI. If that is the case then it probably makes sense to open an issue on [devcontainers/cli](https://github.com/devcontainers/cli) as that is the underpinning of the functionality in the action

Maybe...

**Comment by stuartleeks** [comment]
Thanks @eitsupi. Looking at the output you pasted, the error is indeed coming from the CLI so the related issue you created seems like the best way to continue the discussion 👍

**Comment by Clockwork-Muse** [comment]
As an additional reason why this behavior is desired:
Currently in VS Code if the `devcontainer.json` is in a direct subdirectory of `.devcontainer`, it will notice the file, and can prompt you if there are multiple.  If it's in the required sub-sub directory (ie, `.devcontainer/somesubdir/.devcontainer/devcontainer.json`) VSCode won't find it.

This is handy to account for things like split build/run images (to account for cases where caching doesn't work as well as would be preferred).

**Comment by edward-encoord** [comment]
Another workaround is to copy `.devcontainer/*/devcontainer.json` to a sub-folder before using the devcontainer CI.

Need to pay attention to the values that depend on the location of `devcontainer.json`, like the value of `context` of `build` in `devcontainer.json`.

**Comment by jrhemstad** [comment]
I'd like to see this happen as well. In my project we've got numerous devcontainers for [various build environment configurations](https://github.com/NVIDIA/cccl/tree/main/.devcontainer) (different compilers, etc.).

**Comment by jeffmur** [comment]
This is working as expected on `v3.0` 🎉 

Structure
```
.devcontainer
├── ci
│   └── devcontainer.json
└── prod
    └── devcontainer.json
```

Github Action
```
    - name: Run make ci-build in dev container
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/NAMESPACE/REPO
        configFile: ./.devcontainer/ci/devcontainer.json
        push: never
        runCmd: make build
```

Limitation:
Using `configFile` does not support artifacts nested within the sub directory. 

.devcontainer.json
```json
{
  "name": "Hello World",
  "build": {
    "dockerfile": "Dockerfile"
  },
  "postCreateCommand": ".devcontainer/ci/install.sh",
}
```

Structure
```
.devcontainer
└── ci
    ├── devcontainer.json
    ├── Dockerfile
    ├── README.md
    └── install.sh
```

```bash
Error: Dev container up failed: Command failed: /bin/sh -c .devcontainer/ci/install.sh (exit code: undefined)
```
